language: csharp
dist: trusty
sudo: false
mono: none
dotnet: 2.2.100
script: "./build.sh"
git:
  depth: false
env:
  global:
    secure: h3QQLg4VMpIPr8ihaZeO5UhryKy/xwT4H81n2NSQJGUeMxXoylnUmmCX9Ya+u9yUFudSFP6ZsuQVCTFDmXEFmRId/zrUxzCiqu7Evs8XobBsECl0rzxmOIJzoCGmJG+cbynQvk3gqDdMTD2nLk+YH2C3exQZzn7dlJfk2JBrKR11ykh+OLad7b48RAdUgjswMnj+z1bho5gqNfzkWmQRabmO/858Idxsw+3LqvRBlWrlMfwCcbaYlMXBzn6cOGyUwSpg7+ob+UxFl80C2saYrpQU4M7RHSPsI+C9NBP0sYGZ6l0euHZdBcWWdKqxN2xa61KJ0Solhf6Q2pX5725duENqBd+5vFmvGqoq0FY7ySAi37oTJs4vDQbkFPfymahpWybHg/uFwl4yvuIazkN36l5i4ElJoFa+nBWAr3a0sQrIvn1ZCNOBIlmmf1AdRdC28efrdH4mKiZnH4vi9dkRNa9eGUmKVpyyHbJQJt5k552iV6SNmPruY/9SfVlfsk/5DzNwh0CH5c63X41Sexu9vvN1Kx23uj0DE6rE48ZBpmjrxWtDofEepP7a6L7n9t8Obq/9e3ZivsRFZVI87UKhDXhwGO18fA/q/ZZ9vXWArKmLcCHIHBGZVvSwPCSG16mKE6l5ITxWubICKYhzBkMEiXR+XL1nQ8JDl7RW47JH830=
